name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update package repos
      run: sudo apt-get update
    - name: Install required packages
      run: sudo apt-get install libreadline-dev libncurses5-dev
    - name: make
      run: make linux
    - name: make test
      run: make test
